import os
import sys
from fpdf import FPDF

class EcoTrackPDF(FPDF):
    def header(self):
        # Only draw header on pages after the cover page
        if self.page_no() > 1:
            self.set_font('Helvetica', 'B', 8)
            self.set_text_color(16, 185, 129)  # Eco Green
            self.cell(0, 10, 'ECOTRACK AI ANIMAL WELFARE ECOSYSTEM - ARCHITECTURE & CODEBASE GUIDE', 0, 1, 'R')
            self.set_draw_color(226, 232, 240)  # Slate divider
            self.line(10, 18, 200, 18)
            self.ln(5)

    def footer(self):
        if self.page_no() > 1:
            self.set_y(-15)
            self.set_font('Helvetica', 'I', 8)
            self.set_text_color(148, 163, 184)  # Slate Muted
            # Draw page number centered
            self.cell(0, 10, f'Page {self.page_no()} of {{nb}}', 0, 0, 'C')

    def chapter_title(self, num, title):
        self.set_font('Helvetica', 'B', 14)
        self.set_text_color(30, 41, 59)  # Dark Slate
        self.cell(0, 10, f'{num}. {title}', 0, 1, 'L')
        self.ln(2)

    def section_title(self, title):
        self.set_font('Helvetica', 'B', 11)
        self.set_text_color(16, 185, 129)  # Eco Green
        self.cell(0, 6, title, 0, 1, 'L')
        self.ln(1)

    def paragraph(self, text, font_style='', size=10, text_color=(51, 65, 85)):
        self.set_font('Helvetica', font_style, size)
        self.set_text_color(*text_color)
        self.multi_cell(0, 5, text)
        self.ln(2)

    def code_box(self, text):
        self.set_font('Courier', '', 8)
        self.set_text_color(15, 23, 42)
        self.set_fill_color(248, 250, 252)
        self.set_draw_color(226, 232, 240)
        # Multi-cell with fill background
        self.multi_cell(0, 4, text, border=1, fill=True)
        self.ln(3)

def create_report():
    pdf = EcoTrackPDF()
    pdf.alias_nb_pages()
    pdf.set_auto_page_break(auto=True, margin=20)
    
    # -------------------------------------------------------------
    # PAGE 1: COVER PAGE
    # -------------------------------------------------------------
    pdf.add_page()
    
    # Background decorative color bar
    pdf.set_fill_color(16, 185, 129)  # Eco Green
    pdf.rect(0, 0, 10, 297, 'F')
    
    pdf.set_left_margin(20)
    pdf.ln(40)
    
    # Main Title
    pdf.set_font('Helvetica', 'B', 28)
    pdf.set_text_color(30, 41, 59)  # Dark Slate
    pdf.multi_cell(0, 12, 'EcoTrack AI\nAnimal Welfare Ecosystem')
    pdf.ln(10)
    
    # Subtitle
    pdf.set_font('Helvetica', 'B', 16)
    pdf.set_text_color(16, 185, 129)  # Eco Green
    pdf.multi_cell(0, 8, 'Comprehensive Architecture, Codebase & Data Guide')
    pdf.ln(15)
    
    # Separator Line
    pdf.set_draw_color(203, 213, 225)
    pdf.line(20, 110, 180, 110)
    pdf.ln(20)
    
    # Summary Paragraph
    summary_text = (
        "This document provides a detailed reference of the EcoTrack application architecture, "
        "files, and functions. It details the interaction flow between the React Native Mobile "
        "Frontend, the Vanilla JavaScript Web Frontend, and the Node.js Express Backend. "
        "Furthermore, it covers the offline-capable storage systems, SQLite relational databases, "
        "machine learning models, and biological datasets integrated within the ecosystem."
    )
    pdf.paragraph(summary_text, size=11, text_color=(71, 85, 105))
    
    pdf.ln(50)
    
    # Metadata
    pdf.set_font('Helvetica', 'B', 10)
    pdf.set_text_color(30, 41, 59)
    pdf.cell(0, 6, 'Created For: EcoTrack Engineering Team', 0, 1)
    pdf.set_font('Helvetica', '', 10)
    pdf.cell(0, 6, 'Version: 4.0 Stable Production Build', 0, 1)
    pdf.cell(0, 6, 'Date: August 2026', 0, 1)
    pdf.cell(0, 6, 'Generated by: Antigravity AI Coding Assistant', 0, 1)
    
    # Reset Margin
    pdf.set_left_margin(10)

    # -------------------------------------------------------------
    # PAGE 2: ARCHITECTURE & COMPONENT FLOW
    # -------------------------------------------------------------
    pdf.add_page()
    pdf.chapter_title('1', 'System Architecture Overview')
    
    intro_arch = (
        "EcoTrack is built as an offline-first, high-performance hybrid ecosystem designed to log environmental "
        "impact points (carbon reduction offsets) and run real-time computer vision animal diagnostics. The system "
        "consists of three major layers:\n\n"
        "1. Mobile Frontend: A React Native Expo application written in TypeScript (TSX) that targets iOS and Android. "
        "It runs standard client-side sensor checks, caches coordinates, and coordinates complex camera scanner buffers.\n"
        "2. Web Frontend: A responsive web dashboard (index.html, styles.css, app.js) designed using vanilla JavaScript "
        "for zero dependency load speeds, which hosts web-native diagnostic suites.\n"
        "3. Backend APIs: A Node.js Express server acting as the coordination hub. It registers endpoints for user registration, "
        "data synchronizations, and routes heavy image processing datasets through local TensorFlow models."
    )
    pdf.paragraph(intro_arch)
    
    pdf.section_title('Architecture Data & Service Flow Diagram')
    
    # Use Text-based flow chart to represent the architecture clearly
    flow_diagram = (
        "  +-------------------------------------------------------------+\n"
        "  |                      CLIENT INTERFACES                      |\n"
        "  |  [Mobile App: Expo React Native]     [Website: HTML/CSS/JS] |\n"
        "  +-------------------------------+------------------+----------+\n"
        "                                  |                  |\n"
        "                        HTTP API Requests       HTTP API Requests\n"
        "                        (Base64 images, CRUD)   (Local fallbacks)\n"
        "                                  v                  v\n"
        "  +-------------------------------------------------------------+\n"
        "  |                     EXPRESS API SERVER                      |\n"
        "  |                  (backend/index.js:5000)                    |\n"
        "  +-------+--------------------+---------------------+----------+\n"
        "          |                    |                     |\n"
        "    Queries / Saves       Queries / Saves       Passes Frames\n"
        "          v                    v                     v\n"
        "  +---------------+    +---------------+    +-------------------+\n"
        "  |  USER DATA    |    | SOCIAL ENGINE |    | AI DIAGNOSTIC SEC |\n"
        "  | (db.js & JSON)|    | (social_db.db)|    | (COCO-SSD / PyT)  |\n"
        "  +---------------+    +---------------+    +-------------------+\n"
    )
    pdf.code_box(flow_diagram)
    
    pdf.paragraph(
        "Offline-Capable Logic: If the Express API Server goes offline, both client layers continue operating. "
        "The Website automatically redirects SQL queries to the local browser Storage Engine (social_db.js -> localStorage), "
        "while the Mobile Frontend manages localized coordinate analysis and logs inputs, syncing back to the backend once a "
        "200 OK connection is re-established."
    )

    # -------------------------------------------------------------
    # PAGE 3: FRONTEND MOBILE APP CODEBASE
    # -------------------------------------------------------------
    pdf.add_page()
    pdf.chapter_title('2', 'Frontend Mobile Application (React Native)')
    
    pdf.paragraph(
        "The mobile app is located in /frontend. It is built as a TypeScript Expo project. "
        "Below is an exhaustive folder breakdown with the responsibility of each file:"
    )
    
    pdf.section_title('Core Configurations')
    pdf.paragraph(
        "- app.json: Application metadata, viewport parameters, platform permissions (Camera, Location, Media Library).\n"
        "- package.json: Lists mobile client libraries (Expo modules, React Navigation, React Native Reanimated, etc.).\n"
        "- tsconfig.json: Configuration options for strict TypeScript compilations."
    )
    
    pdf.section_title('Routing & Screens (app/ directory)')
    pdf.paragraph(
        "- _layout.tsx: The root navigation container. Registers Theme Providers and coordinates authentication flow routing.\n"
        "- index.tsx: Startup landing component that parses local authentication tokens to redirect users.\n"
        "- auth.tsx & auth/: Signin, signup, forgot password, OTP verification, and password reset views.\n"
        "- modal.tsx: A customizable modal panel used for details overlays and confirmation popups.\n"
        "- motionGenerator.tsx: Developer-only diagnostic view that runs automated joint vectors to test skeleton trackers.\n"
        "- scanReport.tsx: Compiles details from camera scans. Renders the custom joint angle analysis grids, details "
        "joint deviations, specifies carbon points earned, and outputs custom veterinary coaching tips."
    )

    pdf.section_title('Bottom Tab Screens (app/(tabs)/ directory)')
    pdf.paragraph(
        "- _layout.tsx: Standardizes icons, labels, colors, and layout constraints of the main bottom navigation tab bar.\n"
        "- index.tsx: Main user landing dashboard. Displays carbon points, pet logs, and quick access to scanners.\n"
        "- aiScanner.tsx: Scanner interface. Hooks directly into camera hardware, rendering a dynamic overlay bounding box "
        "and coordinates mesh, feeding canvas dimensions into joint tracking functions in real-time.\n"
        "- training.tsx: Exercise and rehabilitation plan workspace. Tracks pet routine progress, joint ranges, and repetitions.\n"
        "- community.tsx: Social networking panel showing user-generated posts, comment logs, and bookmark states.\n"
        "- marketplace.tsx: Lists local eco-friendly products and animal equipment listings.\n"
        "- events.tsx: Campaign board listing tree plantings, vaccination clinics, and volunteer drives.\n"
        "- maps.tsx: Interactive navigation mapping emergency veterinary hospitals and animal shelters nearby.\n"
        "- explore.tsx: Searchable interface for the 10,000+ species biological catalog.\n"
        "- profile.tsx: Displays user biographies, earned badges, community reputation scores, and registered pets."
    )

    # -------------------------------------------------------------
    # PAGE 4: FRONTEND MOBILE APP UTILITIES & HELPERS
    # -------------------------------------------------------------
    pdf.add_page()
    pdf.chapter_title('3', 'Frontend Mobile Utilities & Shared State')
    
    pdf.paragraph(
        "Behind the mobile UI screens lie a robust library of helper functions and local data managers "
        "located inside /frontend/lib, /frontend/services, and /frontend/data."
    )
    
    pdf.section_title('Biomechanical Logic & Algorithms (lib/ directory)')
    pdf.paragraph(
        "- skeletonTemplates.ts: Defines rigid keypoint links (e.g. neck to tail, shoulder to claw) and proportions "
        "for humans and 5 species groups (canine, feline, equine, avian, bovine).\n"
        "- exerciseTemplates.ts: Biomechanics reference containing min/max angles for joint segments (e.g. elbow flexes, "
        "knee bends) across 10 routines per species. Configures vertical/horizontal displacement parameters for rep counters.\n"
        "- jointAnalysis.ts: Handles trigonometry on keypoint coordinates. Uses dot products and arc cosines to compute "
        "exact joint angles. Tracks angle limits to scoring deviations from target exercise models.\n"
        "- aiPipeline.ts: Pipeline coordinator. Captures video frames, runs detection boundaries, resolves classification "
        "confidence scores, and pipes coordinates to joint analysis handlers.\n"
        "- motionGenerator.ts: Simulates continuous coordinate trajectories (sine curves) representing active animal movements, "
        "providing mock inputs to test model performance.\n"
        "- reportGenerator.ts: Generates clean summaries detailing scan results and recommended recovery checklists."
    )
    
    pdf.section_title('Data Store & API Integrations')
    pdf.paragraph(
        "- data/trainingAnalyticsStore.ts: Global state coordinator. Saves active workout logs, joint deviations, and daily streak counts.\n"
        "- data/animals.ts: Static metadata listing popular species classes.\n"
        "- data/posts.js & data/events.js: Mock local data structures for testing UI layouts offline.\n"
        "- services/api.ts: Connects client forms to backend Node APIs. Automatically logs network errors.\n"
        "- services/wikipedia.ts: Directly queries Wikipedia and Wikimedia APIs for species descriptions and images."
    )

    # -------------------------------------------------------------
    # PAGE 5: WEBSITE IMPLEMENTATION
    # -------------------------------------------------------------
    pdf.add_page()
    pdf.chapter_title('4', 'Website Implementation (Vanilla HTML/CSS/JS)')
    
    pdf.paragraph(
        "The website is located in /website. Built as a high-performance web dashboard, it mirrors the features of the mobile app "
        "but runs entirely on vanilla client-side files, avoiding external compiler chains for fast loading."
    )
    
    pdf.section_title('Structure & Styling')
    pdf.paragraph(
        "- index.html: Core page markup. Defines a clean layout with dedicated panels for the Dashboard, "
        "AI Scanner Canvas, Encyclopedia Catalog, Marketplace, and Community Feeds.\n"
        "- styles.css: Premium, responsive CSS stylesheet. Built with a modern dark slate palette, glassmorphism card overlays, "
        "subtle transition animations, and clear media-query breakpoints for mobile and desktop screens."
    )

    pdf.section_title('Javascript Controllers (website/ directory)')
    pdf.paragraph(
        "- app.js: Root client controller. Manages navigation transitions, updates dashboard carbon scores, handles pet logs, "
        "and uses browser geolocation to find shelters.\n"
        "- community.js: Social manager. Renders posts, handles new text creations, toggles like metrics, and formats comment trees.\n"
        "- messaging.js: Manages private messaging, conversation logs, and real-time chat input panels.\n"
        "- profile.js: Feeds data into profile inputs. Renders dynamic carbon offset charts.\n"
        "- social_db.js: API connector. Sends user data, posts, comments, and follows to backend SQLite endpoints. Contains a "
        "fallback system that writes directly to browser localStorage when backend APIs are down, keeping the UI functional.\n"
        "- scanner_engine.js: Browser computer vision engine. Integrates: \n"
        "  * TensorFlow.js (COCO-SSD) to output subject classification boundaries.\n"
        "  * MediaPipe Tasks Vision (PoseLandmarker WASM) to track joint coordinates.\n"
        "  * Browser Canvas API to perform client-side analysis and check canvas boundaries."
    )

    # -------------------------------------------------------------
    # PAGE 6: BACKEND SERVER ARCHITECTURE
    # -------------------------------------------------------------
    pdf.add_page()
    pdf.chapter_title('5', 'Backend Express Server & Database Core')
    
    pdf.paragraph(
        "The backend server is located in /backend. It is powered by Node.js and Express, orchestrating data storage, "
        "machine learning classifications, and social engines."
    )
    
    pdf.section_title('Server Files & Orchestrators')
    pdf.paragraph(
        "- index.js: Main server app. Starts the Express pipeline, enables CORS, registers routing endpoints, and runs TF.js "
        "COCO-SSD in Node environment to host backend object detection. Includes routes for:\n"
        "  * User Auth: Signups, Logins, Password Resets, OTP codes.\n"
        "  * Profiles & Pets: Registering pet profiles, logging vaccinations, editing user profiles.\n"
        "  * Encyclopedia: Querying biological taxons via search filters.\n"
        "  * AI Scanner: /api/ai/detect (Express object checks), /api/ai/pose (maps keypoints), /api/ai/scan-save.\n"
        "  * Social Feed: /api/social routes for posts, follows, bookmarks, comments, and reputation logs.\n"
        "- db.js: Core database manager. Seeds initial profiles, exercises, clinics, and default users. Provides query wrappers "
        "and manages serialization to ecotrack_userdata.json and ecotrack_database.json.\n"
        "- social_sqlite.js: Database setup. Connects to ecotrack_social.db. Defines SQL tables, sets indexes, and seeds starting data."
    )
    
    pdf.section_title('Data Persistence & Files')
    pdf.paragraph(
        "- ecotrack_database.json: File database storing default clinic indexes, exercise metadata, and base system configs.\n"
        "- ecotrack_userdata.json: Primary storage for user records, registered pets, diagnostic logs, and rehab schedules.\n"
        "- ecotrack_social.db: SQLite database storing community posts, replies, follows, user stats, and carbon badges.\n"
        "- encyclopedia.db: Primary taxonomy SQLite database containing 10,000+ biological species records."
    )

    # -------------------------------------------------------------
    # PAGE 7: DATASETS, MODELS & PIPELINES
    # -------------------------------------------------------------
    pdf.add_page()
    pdf.chapter_title('6', 'Biological Datasets, ML Models & Pipelines')
    
    pdf.paragraph(
        "EcoTrack integrates several biological taxonomy datasets and machine learning models to "
        "perform species classification and biomechanical pose tracking."
    )
    
    pdf.section_title('Integrated Datasets')
    pdf.paragraph(
        "1. AP-10K: Animal pose estimation dataset providing keypoint proportions and joint structures for 54 species.\n"
        "2. Animal-Pose: Coordinates for 5 key animal categories (dog, cat, cow, horse, sheep).\n"
        "3. COCO Keypoints: Human body joint schema used to align human coordinates.\n"
        "4. ITIS Database: Integrated Taxonomic Information System SQLite dump used in scripts to extract 10k+ taxonomy records.\n"
        "5. Wikimedia Commons: Wikipedia and media libraries queried during generation to download descriptions and crop images."
    )
    
    pdf.section_title('Machine Learning Models')
    pdf.paragraph(
        "- MediaPipe PoseLandmarker: WASM browser tasks and native bundles tracking 33 skeletal points.\n"
        "- YOLOv8 Pose: YOLO models (yolov8n-pose.pt / yolov8m-pose.pt) used to extract animal silhouettes.\n"
        "- COCO-SSD (MobileNet v2): Multi-class object detector running client-side (TF.js CDN) and server-side (tfjs-node).\n"
        "- Custom PyTorch Classifier (species_model_best.pt): Deep neural network classifying 30 species using a 24-dimensional feature signature."
    )

    pdf.section_title('Build & Pipeline Scripts (/scripts/ directory)')
    pdf.paragraph(
        "- download_datasets_and_models.py: Python script that retrieves YOLO models, MediaPipe files, and dataset configurations.\n"
        "- train_species_model.py: PyTorch training pipeline. Builds a MultiSpeciesPoseClassifierNet, verifies inputs, and outputs weights.\n"
        "- generate_encyclopedia_dataset.js: Extracts ITIS records, queries Wikimedia API for common names and images, and builds encyclopedia.db.\n"
        "- rebuild_species_image_cache.js & verify_species_images.js: Manages downloading and validating taxonomy images.\n"
        "- build_db_from_userdata.js / clean_wiki_urls.js / fetch_verified_urls.js: Clean up dataset caches and convert JSON storage."
    )

    # -------------------------------------------------------------
    # PAGE 8: FLOW OF ARCHITECTURE & USER DATA persistence
    # -------------------------------------------------------------
    pdf.add_page()
    pdf.chapter_title('7', 'User Data Flow & Languages Used')
    
    pdf.section_title('How User Data is Saved')
    pdf.paragraph(
        "1. Authentication: When a user signs up/logs in, Express checks the social database. Password hashing is validated, and an ecotrack_id is returned.\n"
        "2. User Profiles & Pet Logs: Pet health logs, exercise parameters, and app configs are written to backend/db.js which serializes them to JSON files (ecotrack_userdata.json).\n"
        "3. Social Interactions & Badges: Posts, comments, likes, replies, follows, and reputation metrics are saved in ecotrack_social.db.\n"
        "4. Web Storage Fallback: If network connectivity drops, website/social_db.js writes directly to localStorage. Upon reconnecting, data is synchronized."
    )
    
    pdf.ln(2)
    pdf.section_title('Programming Languages Used in the Project')
    
    # Table layout for languages
    pdf.set_font('Helvetica', 'B', 9)
    pdf.set_text_color(30, 41, 59)
    pdf.cell(50, 6, 'Language', 1, 0, 'L')
    pdf.cell(50, 6, 'Project Layer', 1, 0, 'L')
    pdf.cell(90, 6, 'Usage Details', 1, 1, 'L')
    
    pdf.set_font('Helvetica', '', 8)
    languages = [
        ('TypeScript (.ts/.tsx)', 'Mobile App Frontend', 'Expo / React Native UI components, logic, contexts, state stores.'),
        ('JavaScript (.js)', 'Web Frontend, Server & Scripts', 'Web app controllers, Node Express routing, database managers, and pipelines.'),
        ('Python (.py)', 'ML Training & Data Pipelines', 'PyTorch network modeling, downloading datasets, and training classifiers.'),
        ('HTML & CSS (.html/.css)', 'Web User Interface', 'Document structure layout and glassmorphic premium stylesheet.'),
        ('SQL', 'Database Layer', 'Table structures, indexes, and queries in SQLite files.')
    ]
    for lang, layer, detail in languages:
        pdf.cell(50, 6, lang, 1, 0, 'L')
        pdf.cell(50, 6, layer, 1, 0, 'L')
        pdf.cell(90, 6, detail, 1, 1, 'L')
        
    pdf.ln(5)
    pdf.section_title('Architecture Flow Summary')
    pdf.paragraph(
        "All data and ML requests originate in either the Mobile client or the Website, moving through "
        "local client ML logic before sending payload calls to the Node.js APIs. The server processes raw pixel data, "
        "queries the SQLite taxonomy catalogs, updates databases, and returns unified status reports, "
        "ensuring a highly responsive and offline-functional animal welfare diagnostic workspace."
    )
    
    # Output file
    output_path = r'c:\Users\DELL\EcoTrackApp\EcoTrack_Architecture_Guide.pdf'
    pdf.output(output_path)
    print(f"PDF generated successfully at {output_path}")

if __name__ == '__main__':
    create_report()
